### ISSUE TITLE
sunburst_data: Invalid syntax

### ISSUE THREAD

**Issue by basille** [didacs/ggsunburst#1] opened 2020-07-02 11:07 UTC
Hi, I found this interesting package through Slack Overflow to create sunburst diagrams. I wanted to test it with simple data, but keep getting an invalid syntax error. Example (from the README, but same error from other examples found online):

```
> library(ggsunburst)
> nw <- "(((a, b, c), (d, e, f, g)), (f, i, h));"
> sb <- sunburst_data(nw)
Error in py_run_file_impl(file, local, convert) : 
  SyntaxError: invalid syntax (<string>, line 31)
```

Maybe related to an update in the underlying libraries?

**Comment by didacs** [comment] 2020-07-04 14:46
Hi basille, the problem is that the package is not compatible with python 3. Currently it uses an old version of the ete2 python package and I would need to update that part in order for ggsunburst to be compatible with python 3. As a workaround you can specify a python 2 in your system. In my case this works

```
library(devtools)
install_github("didacs/ggsunburst")
library(ggsunburst)
use_python("/usr/bin/python") # this is python 2.7.10 in my system
nw <- "(((a, b, c), (d, e, f, g)), (f, i, h));"
sb <- sunburst_data(nw)

```

**Comment by basille** [comment] 2020-07-15 10:52
Thanks for looking into it! So that was a python version issue… On my system, I get:

```
~$ /usr/bin/python --version
Python 2.7.13
```

But your proposed solution does not seem to fix the issue on my system as I get the same error:

```
> sb <- sunburst_data(nw)
Error in py_run_file_impl(file, local, convert) : 
  SyntaxError: invalid syntax (<string>, line 31)
In addition: Warning message:
Python '/usr/bin/python' was requested but '/home/mathieu/.local/share/r-miniconda/envs/r-reticulate/bin/python' was loaded instead (see reticulate::py_config() for more information) 
```

… which seems to come from the last part of it, i.e. using Python in `~/.local/share/r-miniconda/envs/r-reticulate/bin/python` instead, which is version 3:

```
~$ /home/mathieu/.local/share/r-miniconda/envs/r-reticulate/bin/python --version
Python 3.6.10 :: Anaconda, Inc.
```

At this stage, this seems more like an issue with `reticulate`, but I am not familiar with either Python or `reticulate`. Any idea how to resolve this?

**Comment by didacs** [comment] 2020-07-27 20:59
Hi basille,
I have updated ggsunburst with etetoolkit version 3, so now it should work without having to specify python2.
Could you please give it a try?
delete the current version and install it from github

```
remove.packages('ggsunburst')
library(devtools)
install_github("didacs/ggsunburst")
library(ggsunburst)
nw <- "(((a, b, c), (d, e, f, g)), (f, i, h));"
sb <- sunburst_data(nw)

```
 make sure that version 0.3.0 was installed
Thanks!

**Comment by basille** [comment] 2020-08-03 11:11
Fantastic, that works beautifully now! Thanks for the fix!

**Comment by didacs** [comment] 2020-08-03 13:36
Great! I am closing this issue

**Closed as completed by didacs** 2020-08-03 13:36 UTC
